Second Milestone
nriqu322/ror-social-scaffold pull request #2
Opened 2020-05-01 17:50 UTC by sz16900

- Created a model with associations and all requested features for friendships:

  - I want to be able to send a friendship invitation.
  -I want to see a button “Invite to friendship” next to the name of the user who is not my friend yet - 
   on both users’ list and single-user page.
  -I want to be able to see pending friendship invitations sent to me from other users.
  -I want to be able to accept or reject friendships invitation.

- Added Unit tests for models: User + Friendship

2020-05-04 00:09 UTC, mosaaleb requested changes
#### Well done @sz16900 @nriqu322 :clap:

You have done a great job, still, there are some requirements we need to achieve before moving on.


- [x] Posts timeline includes posts written by logged-in user and their friends -- our current implementation displays all posts for all users, even if we aren't friends with.

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png)

- [x] Great job adding unit tests, it covers all cases. But we still need to add integration tests (capybara)


![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png)

Feel free to contact me on slack if you have any questions.

Please handle these requirements and submit a new code review.

##### Muhammad Ebeid

2020-05-04 00:09 UTC, mosaaleb commented on app/models/user.rb
> +  # Set confirmation to true
- [x] Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history

2020-05-04 00:09 UTC, mosaaleb commented on app/models/friendship.rb
> +  belongs_to :friend, class_name: 'User'
- [x] **[OPTIONAL]** I suggest that you add uniqueness validations on `[user_id, friend_id]` combination on friendships table so that we won't have unnecessary duplicate records if there is any bug in our views. This way we ensure the integrity of our data.

Take a look at [this](https://stackoverflow.com/questions/29123620/rails-validate-unique-friendship-relationships)

2020-05-04 00:09 UTC, mosaaleb commented on app/controllers/friendships_controller.rb
> +  def edit
- [x] **[OPTIONAL]** Instead of having (if else) inside `edit` action to decide what to do depending on accepting or rejecting, we can refactor this by changing our routes to map to `update` action in case of "accepting", and to `destroy` action in case of "rejecting" a friendship. This way we have achieved more concern separation.

2020-05-04 00:09 UTC, mosaaleb commented on app/views/users/index.html.erb
> +        <% if current_user.pending_friends.include?(user) %>
- [ ] There shoud be absolutely NO logic in views. View related logic should be encapsulated in View [helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers).

2020-05-04 00:09 UTC, mosaaleb commented on app/views/users/show.html.erb
> +        <% if current_user.pending_friends.include?(@user) %>
- [ ] Same for using helpers for encapsulating view logic. Using helpers will allow us to extract the duplicated code that we have in `show` and `index` templates.

2020-05-05 21:31 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @sz16900 and @nriqu322  :balloon: :lollipop: 

### Thank you for doing some of the changes requested by the previous reviewer,  your friendships are working as expected :medal_sports: :medal_sports: claps for putting the logic in helpers instead of the views :clap: :clap: :clap: , that been said I think you still have to work on your integration test cases :construction: :construction_worker: :construction_worker: 

#### Project-specific

* [x] **Unit and Integration Test Cases** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)) I see you've added integration test cases for creating users, post, and likes and you only have unit test cases for your friendships but I'd like you to add integration test cases for friendships because you work with friendships in this milestone Please add test cases that validates these scenarios:

- Send friend request (either from the user's index or show page or both)
- Accept friendship (either from the user's index or show page or both)
- Decline friendship (either from the user's index or show page or both)
- [OPTIONAL] See posts from the current user and his or her friends in the Timeline

## [OPTIONAL] 
* [x] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- you don't have a button it's a link and it looks like part of the description, I'm setting it as optional because the previous reviewer didn't mention it but this is part of the requirements

![image](https://user-images.githubusercontent.com/52209067/81117960-38cf8300-8ee5-11ea-8d41-b7e5f2681d30.png)


### That's it! :raised_hands: 

### Please :pray:  do the changes :man_technologist: :man_technologist:  and submit back for a code review when you are done :memo: 

Happy Coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-05-06 21:52 UTC, nikasulo approved these changes
# Great work! @sz16900 and @nriqu322! :medal_military: 
Please merge and keep moving forward! I wish you the very best and see you at the top! :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-05-06 22:02 UTC, merged